export default [
  {
    id: "1",
    title: "Drug 20% off",
    image: require("../../assets/MyImages/f1.png"),
    rate: 4.6,
    time: "10:14 AM",
    day: 'Today',
    discreption:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed",
    quantity: 3,
  },
  {
    id: "2",
    title: "Suligga Max 10%",
    image: require("../../assets/MyImages/f1.png"),
    rate: 5,
    time: "02:30 AM",
    day: 'Today',
    discreption:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed",
    quantity: 4,
  },
  {
    id: "3",
    title: "Sunday Offer",
    image: require("../../assets/MyImages/f1.png"),
    rate: 5,
    time: "03:18 AM",
    day: 'Yesterday',
    discreption:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed",
    quantity: 3,
  },
  {
    id: "4",
    title: "Star Sunday Offer",
    image: require("../../assets/MyImages/f1.png"),
    rate: 5,
    time: "04:14 AM",
    day: 'Yesterday',
    discreption:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed",
    quantity: 7,
  },
  {
    id: "5",
    title: "Biggest Offers",
    image: require("../../assets/MyImages/f1.png"),
    rate: 5,
    time: '06:20 AM',
    day: 'Last week',
    discreption:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed",
    quantity: 1,
  },
  {
    id: "6",
    title: "Biggest Offers",
    image: require("../../assets/MyImages/f1.png"),
    rate: 5,
    time: '06:20 AM',
    day: 'Last week',
    discreption:"Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed",
    quantity: 1,
  },
];

