export default [
  {
    id: "1",
    title: "AER569326",
    image: require("../../assets/MyImages/f1.png"),
    rate: 4.6,
    time: "10:14 AM",
    day: 'Today',
    discreption:"11/B,Vest surat - 5696",
    quantity: 3,
  },
  {
    id: "2",
    title: "DWE598635",
    image: require("../../assets/MyImages/f1.png"),
    rate: 5,
    time: "02:30 AM",
    day: 'Today',
    discreption:"11/B,Vest surat - 5696",
    quantity: 4,
  },
  {
    id: "3",
    title: "DFG 256821",
    image: require("../../assets/MyImages/f1.png"),
    rate: 5,
    time: "03:18 AM",
    day: 'Yesterday',
    discreption:"11/B,Vest surat - 5696",
    quantity: 3,
  },
  {
    id: "4",
    title: "KOS458936",
    image: require("../../assets/MyImages/f1.png"),
    rate: 5,
    time: "04:14 AM",
    day: 'Yesterday',
    discreption:"11/B,Vest surat - 5696",
    quantity: 7,
  },
  {
    id: "5",
    title: "WER879635",
    image: require("../../assets/MyImages/f1.png"),
    rate: 5,
    time: '06:20 AM',
    day: 'Last week',
    discreption:"11/B,Vest surat - 5696",
    quantity: 1,
  },
  {
    id: "6",
    title: "NDS256358",
    image: require("../../assets/MyImages/f1.png"),
    rate: 5,
    time: '06:20 AM',
    day: 'Last week',
    discreption:"11/B,Vest surat - 5696",
    quantity: 1,
  },
  {
    id: "7",
    title: "Low Blush Bean",
    image: require("../../assets/MyImages/f1.png"),
    Variation : 'Yellow, XXL',
    paymentStatus: 'Already paid',
    price:596,
    totalOrder:3,
  },
];


//